/* AUTOGENERATED by _gen_ui.py - edit the generator, not this file. */
(function () {
  var Q = window.QwenPaw;
  if (!Q || !Q.host || !Q.host.React || !Q.registerRoutes) return;
  var React = Q.host.React;
  var antd = Q.host.antd;
  var h = React.createElement;
  var Fragment = React.Fragment;
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useRef = React.useRef;
  var APP = "/zhiyun-supply-studio";
  var ID = "zhiyun-supply-studio";

  var T = {
    bg: "#f4f6f9", panel: "#ffffff", inset: "#f8fafc", border: "#e3e8ef",
    borderStrong: "#d3dae3", text: "#1f2933", sub: "#5b6472", faint: "#98a2b3",
    primary: "#2563eb", primaryDark: "#1d4ed8", primarySoft: "#eff6ff",
    green: "#16a34a", amber: "#d97706", red: "#dc2626", violet: "#6d28d9",
    cyan: "#0891b2", radius: 8, radiusLg: 10,
    shadow: "0 1px 2px rgba(16,24,40,0.04), 0 2px 6px rgba(16,24,40,0.06)"
  };
  var APP_TITLE = "智能供应链中心";
  var APP_SUBTITLE = "供应商多维评估、补货决策建议与供应链风险实时监控";
  var CSS_ID = "zy-" + ID + "-css";
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var style = document.createElement("style");
    style.id = CSS_ID;
    style.textContent = [
      ".zy-app,.zy-app *{box-sizing:border-box;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Microsoft YaHei',sans-serif;}",
      ".zy-app{background:" + T.bg + ";min-height:100%;}",
      ".zy-topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:14px;padding:14px 104px 14px 24px;background:rgba(255,255,255,0.92);backdrop-filter:blur(8px);border-bottom:1px solid " + T.border + ";}",
      ".zy-monogram{width:38px;height:38px;border-radius:10px;background:" + T.primary + ";color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:16px;flex:0 0 auto;box-shadow:" + T.shadow + ";}",
      ".zy-topbar-title{font-weight:650;font-size:16px;color:" + T.text + ";line-height:1.2;}",
      ".zy-topbar-sub{font-size:12px;color:" + T.sub + ";margin-top:2px;}",
      ".zy-body{display:flex;gap:20px;max-width:1360px;margin:0 auto;padding:20px 24px 40px;}",
      ".zy-rail{width:224px;flex:0 0 auto;background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:" + T.radiusLg + "px;padding:10px;height:fit-content;position:sticky;top:84px;}",
      ".zy-rail-label{font-size:11px;color:" + T.faint + ";letter-spacing:.04em;margin:4px 8px 8px;font-weight:600;}",
      ".zy-nav-item{display:flex;align-items:flex-start;gap:10px;padding:11px;border-radius:9px;cursor:pointer;border:1px solid transparent;transition:all .18s ease;}",
      ".zy-nav-item:hover{background:" + T.inset + ";}",
      ".zy-nav-item.zy-active{background:" + T.primarySoft + ";border-color:#c7dcff;}",
      ".zy-nav-ico{width:30px;height:30px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:15px;background:" + T.inset + ";border:1px solid " + T.border + ";flex:0 0 auto;}",
      ".zy-nav-item.zy-active .zy-nav-ico{background:" + T.primary + ";color:#fff;border-color:" + T.primary + ";}",
      ".zy-nav-name{font-size:13px;font-weight:600;color:" + T.text + ";line-height:1.3;}",
      ".zy-nav-desc{font-size:11px;color:" + T.sub + ";margin-top:3px;line-height:1.4;}",
      ".zy-main{flex:1 1 auto;min-width:0;}",
      ".zy-panel{background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:" + T.radiusLg + "px;box-shadow:" + T.shadow + ";}",
      ".zy-panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid " + T.border + ";}",
      ".zy-panel-title{font-size:14px;font-weight:650;color:" + T.text + ";}",
      ".zy-panel-sub{font-size:12px;color:" + T.sub + ";margin-top:3px;}",
      ".zy-panel-body{padding:16px 18px;}",
      ".zy-cols{display:grid;grid-template-columns:minmax(360px,0.92fr) minmax(0,1.08fr);gap:16px;align-items:start;}",
      ".zy-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;}",
      ".zy-define h4{font-size:12px;color:" + T.faint + ";font-weight:600;margin:0 0 8px;}",
      ".zy-define p{font-size:12px;color:" + T.sub + ";line-height:1.55;margin:0;}",
      ".zy-answer{white-space:pre-wrap;font-size:13px;color:" + T.text + ";line-height:1.7;background:" + T.inset + ";border:1px solid " + T.border + ";border-radius:9px;padding:14px 16px;}",
      ".zy-tagline{font-size:12px;color:" + T.sub + ";line-height:1.5;}",
      ".zy-fade{animation:zyFade .28s ease both;}",
      "@keyframes zyFade{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}",
      ".zy-mask{position:fixed;inset:0;background:rgba(15,23,42,0.32);z-index:1000;animation:zyFade .18s ease both;}",
      ".zy-dock{position:fixed;top:0;right:0;bottom:0;width:min(420px,92vw);background:" + T.panel + ";border-left:1px solid " + T.border + ";box-shadow:-10px 0 30px rgba(16,24,40,0.16);z-index:1001;display:flex;flex-direction:column;animation:zyFade .22s ease both;}",
      ".zy-chat{display:flex;flex-direction:column;height:100%;}",
      ".zy-chat-head{padding:14px 16px;background:" + T.panel + ";border-bottom:1px solid " + T.border + ";}",
      ".zy-chat-list{flex:1 1 auto;overflow:auto;padding:16px;}",
      ".zy-msg{display:flex;flex-direction:column;gap:6px;margin-bottom:14px;}",
      ".zy-msg-bubble{max-width:92%;padding:10px 12px;border-radius:11px;font-size:12.5px;line-height:1.6;box-shadow:" + T.shadow + ";}",
      ".zy-msg-user{align-items:flex-end;}",
      ".zy-msg-user .zy-msg-bubble{background:" + T.primary + ";color:#fff;border-bottom-right-radius:3px;}",
      ".zy-msg-bot{align-items:flex-start;}",
      ".zy-msg-bot .zy-msg-bubble{background:" + T.panel + ";border:1px solid " + T.border + ";border-bottom-left-radius:3px;color:" + T.text + ";}",
      ".zy-msg-card{max-width:92%;background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:11px;padding:12px 14px;box-shadow:" + T.shadow + ";}",
      ".zy-chat-input{padding:12px 14px;background:" + T.panel + ";border-top:1px solid " + T.border + ";}",
      ".zy-chips{display:flex;flex-wrap:wrap;gap:8px;}",
      ".zy-chip{border:1px solid " + T.border + ";background:" + T.panel + ";border-radius:999px;padding:6px 12px;font-size:12px;color:" + T.sub + ";cursor:pointer;transition:all .16s ease;user-select:none;}",
      ".zy-chip:hover{border-color:" + T.primary + ";color:" + T.primary + ";background:" + T.primarySoft + ";}",
      ".zy-status-dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:6px;}",
      ".zy-run{transition:transform .16s ease;}",
      ".zy-run:hover{transform:translateY(-1px);}",
      ".zy-hint{font-size:12px;color:" + T.sub + ";line-height:1.6;background:" + T.inset + ";border:1px dashed " + T.border + ";border-radius:9px;padding:10px 12px;}",
      ".zy-cellgap th,.zy-cellgap td{padding:9px 8px!important;vertical-align:top;}",
      "@media(max-width:980px){.zy-body{flex-direction:column;padding:16px;}.zy-rail{width:100%;position:static;top:auto;}.zy-cols{grid-template-columns:1fr;}}"
    ].join("\n");
    document.head.appendChild(style);
  }
  ensureCss();

  function request(path, body) {
    return Q.host.fetch(path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body)
    }).then(function (response) {
      return response.json().then(function (data) {
        if (!response.ok) throw new Error(data.detail || ("HTTP " + response.status));
        return data;
      });
    });
  }
  function getJson(path) {
    return Q.host.fetch(path).then(function (response) { return response.json(); });
  }
  function pushAgentContext(ctx) {
    if (Q.setAgentContext) Q.setAgentContext(ctx);
    else window.dispatchEvent(new CustomEvent("qwenpaw:agent-context", { detail: ctx }));
  }
  function fmt(value) { return value == null || value === "" ? "—" : String(value); }
  function isBlank(value) { return value == null || value === "" || (Array.isArray(value) && !value.length); }
  function clone(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
  function sampleFor(mod) { return mod.sample != null ? mod.sample : mod.example; }
  var __ridSeq = 10000;
  function nextRid() { __ridSeq += 1; return "r" + __ridSeq; }
  function withRid(rows) {
    return (rows || []).map(function (r) {
      if (r && r.__rid) return r;
      var copy = Object.assign({}, r || {});
      copy.__rid = nextRid();
      return copy;
    });
  }
  function stripRid(value) {
    if (Array.isArray(value)) return value.map(stripRid);
    if (value && typeof value === "object") {
      var out = {};
      Object.keys(value).forEach(function (k) { if (k !== "__rid") out[k] = stripRid(value[k]); });
      return out;
    }
    return value;
  }
  function statusTone(status) {
    if (status === "accepted") return { color: "green", text: "已接受" };
    if (status === "rejected") return { color: "red", text: "已驳回" };
    return { color: "orange", text: "待审阅" };
  }
  function statusColor(status) {
    if (status === "紧急补货") return "red";
    if (status === "建议补货") return "orange";
    if (status === "库存充足") return "green";
    if (status === "达标") return "green";
    if (status === "接近") return "orange";
    if (status === "落后") return "red";
    return "default";
  }

  function RefreshIcon() {
    return h("span", { style: { fontSize: 13 } }, "⟳");
  }
  function SparkIcon() { return h("span", { style: { fontSize: 13 } }, "✦"); }
  function AgentIcon() { return h("span", { style: { fontSize: 13 } }, "✦"); }

  function AppHeader(props) {
    return h("div", { className: "zy-topbar" },
      h("div", { className: "zy-monogram" }, "供应"),
      h("div", { style: { flex: 1, minWidth: 0 } },
        h("div", { className: "zy-topbar-title" }, APP_TITLE),
        h("div", { className: "zy-topbar-sub" }, APP_SUBTITLE)
      ),
      h(antd.Tag, { color: props.source === "演示" ? "purple" : "green", style: { margin: 0 } }, props.source + "数据"),
      h(antd.Button, { size: "small", icon: h(RefreshIcon), onClick: props.onRefresh }, "刷新"),
      h(antd.Button, { size: "small", type: "primary", onClick: props.onAgent }, h(SparkIcon), " 问 Agent")
    );
  }

  function ModuleNav(props) {
    return h("div", { className: "zy-rail" },
      h("div", { className: "zy-rail-label" }, "功能模块"),
      props.modules.map(function (mod) {
        var active = mod.key === props.active;
        return h("div", { key: mod.key, className: "zy-nav-item" + (active ? " zy-active" : ""), onClick: function () { props.onSelect(mod.key); } },
          h("div", { className: "zy-nav-ico" }, mod.icon),
          h("div", { style: { minWidth: 0 } },
            h("div", { className: "zy-nav-name" }, mod.label),
            h("div", { className: "zy-nav-desc" }, mod.short)
          )
        );
      })
    );
  }

  function KpiStrip(props) {
    return h("div", { className: "zy-kpis" },
      (props.items || []).map(function (item) {
        return h("div", { key: item.label, style: { background: T.panel, border: "1px solid " + T.border, borderRadius: 9, padding: "12px 14px", boxShadow: T.shadow } },
          h("div", { style: { fontSize: 11, color: T.faint, fontWeight: 600 } }, item.label),
          h("div", { style: { fontSize: 24, fontWeight: 700, color: item.color || T.text, marginTop: 4, lineHeight: 1.2 } }, item.value)
        );
      })
    );
  }

  function EmptyState(props) {
    return h("div", { style: { textAlign: "center", padding: "52px 20px", color: T.sub } },
      h("div", { style: { fontSize: 40, marginBottom: 12 } }, props.icon),
      h("div", { style: { fontWeight: 650, color: T.text } }, props.title),
      h("div", { style: { fontSize: 12, marginTop: 8, lineHeight: 1.6 } }, props.desc)
    );
  }

  function ReviewBar(props) {
    var tone = statusTone(props.status);
    return h("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginTop: 16, padding: 12, background: T.inset, border: "1px solid " + T.border, borderRadius: 9 } },
      h(antd.Tag, { color: tone.color, style: { margin: 0 } }, tone.text),
      h("span", { style: { fontSize: 12, color: T.sub } }, "Trace " + props.traceId),
      h(antd.Input, { size: "small", value: props.reviewer, onChange: function (e) { props.setReviewer(e.target.value); }, placeholder: "具名审阅人（必填）", style: { width: 160 } }),
      h(antd.Button, { size: "small", type: "primary", disabled: !props.reviewer.trim() || props.status === "accepted", onClick: function () { props.onDecide("accept"); } }, "接受"),
      h(antd.Button, { size: "small", danger: true, disabled: !props.reviewer.trim() || props.status === "rejected", onClick: function () { props.onDecide("reject"); } }, "驳回"),
      h(antd.Button, { size: "small", disabled: props.status !== "accepted", onClick: props.onExport }, "导出"),
      h(antd.Button, { size: "small", onClick: props.onHandoff }, "交给 Agent")
    );
  }

  function InputText(props) {
    return h("div", null,
      h(antd.Input.TextArea, { className: "zy-textarea", value: props.value, rows: props.rows || 7, placeholder: props.placeholder, onChange: function (e) { props.onChange(e.target.value); } }),
      h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginTop: 10 } },
        h("span", { style: { fontSize: 11, color: T.faint } }, "输入真实咨询/业务文本，首次使用可载入示例"),
        h(antd.Button, { size: "small", type: "dashed", onClick: function () { props.onChange(props.example); } }, "载入示例文本")
      ),
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 10 } }, props.hint) : null
    );
  }

  function cellEditor(col, row, index, onCell) {
    var key = col.key;
    var val = row ? row[key] : undefined;
    function set(v) { onCell(index, key, v); }
    if (col.type === "number") {
      return h(antd.InputNumber, { size: "small", value: val === "" || val == null ? undefined : Number(val), min: col.min, max: col.max, step: col.step, style: { width: "100%" }, placeholder: col.placeholder, onChange: function (v) { set(v == null ? "" : v); } });
    }
    if (col.type === "select") {
      return h(antd.Select, { size: "small", value: val, style: { width: "100%" }, placeholder: col.placeholder, options: col.options, onChange: set });
    }
    if (col.type === "tags") {
      return h(antd.Select, { mode: "tags", size: "small", value: val || [], style: { width: "100%" }, placeholder: col.placeholder, options: col.options || [], onChange: set, tokenSeparators: ["，", ",", ";"] });
    }
    return h(antd.Input, { size: "small", value: val, placeholder: col.placeholder, onChange: function (e) { set(e.target.value); } });
  }

  function EditableTable(props) {
    var cols = props.columns;
    var value = props.value || [];
    var rows = withRid(value);
    function change(index, key, v) {
      var next = rows.map(function (r, i) { return i === index ? Object.assign({}, r, (function () { var o = {}; o[key] = v; return o; })()) : r; });
      props.onChange(next);
    }
    function addRow() {
      var blank = {};
      cols.forEach(function (c) { blank[c.key] = c.defaultValue !== undefined ? c.defaultValue : (c.type === "tags" ? [] : (c.type === "select" && c.options && c.options.length ? c.options[0].value : "")); });
      blank.__rid = nextRid();
      props.onChange(value.concat([blank]));
    }
    function removeRow(index) { props.onChange(value.filter(function (_, i) { return i !== index; })); }
    function loadSample() { props.onChange(withRid(clone(props.sample))); }
    var tableCols = cols.map(function (col) {
      return {
        title: col.label + (col.required ? " *" : ""), dataIndex: col.key, key: col.key, width: col.width, ellipsis: false,
        render: function (text, row, index) { return cellEditor(col, row, index, change); }
      };
    }).concat([{ title: "", key: "_op", width: 42, render: function (_, row, index) { return h(antd.Button, { size: "small", type: "text", danger: true, onClick: function () { removeRow(index); } }, "✕"); } }]);
    return h("div", null,
      h("div", { style: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 12, alignItems: "center" } },
        h(antd.Button, { size: "small", type: "primary", onClick: loadSample }, "一键导入示例数据"),
        h(antd.Button, { size: "small", onClick: addRow }, "添加一行"),
        h(antd.Button, { size: "small", danger: true, onClick: function () { props.onChange([]); } }, "清空"),
        h("span", { style: { fontSize: 11, color: T.faint } }, "请在表格内直接编辑，避免手写 JSON")
      ),
      h(antd.Table, { size: "small", rowKey: function (row) { return row && row.__rid ? row.__rid : "r" + Math.random(); }, pagination: false, dataSource: rows, columns: tableCols, className: "zy-cellgap", scroll: { x: Math.max(600, cols.length * 150) } }),
      value.length === 0 ? h(EmptyState, { icon: props.icon || "📄", title: "暂无数据", desc: "点击上方「一键导入示例数据」快速填充，或在表格中逐行录入。" }) : null,
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 12 } }, props.hint) : null
    );
  }

  function editorFor(field, value, setField) {
    if (field.type === "subtable") {
      return h(EditableTable, { icon: field.icon || "🧩", columns: field.columns, value: value || [], onChange: setField, sample: field.sample, hint: field.hint });
    }
    if (field.type === "textarea") {
      return h(antd.Input.TextArea, { size: "small", value: value, rows: field.rows || 4, placeholder: field.placeholder, onChange: function (e) { setField(e.target.value); } });
    }
    if (field.type === "number") {
      return h(antd.InputNumber, { value: value === "" || value == null ? undefined : Number(value), min: field.min, max: field.max, step: field.step, style: { width: "100%" }, placeholder: field.placeholder, onChange: function (v) { setField(v == null ? "" : v); } });
    }
    if (field.type === "select") {
      return h(antd.Select, { value: value, options: field.options, placeholder: field.placeholder, onChange: setField });
    }
    if (field.type === "percent") {
      return h(antd.InputNumber, { value: value === "" || value == null ? undefined : Number(value), min: field.min < 0 ? field.min : 0, max: field.max, step: field.step || 0.01, style: { width: "100%" }, addonAfter: "%", placeholder: field.placeholder, onChange: function (v) { setField(v == null ? "" : v); } });
    }
    return h(antd.Input, { value: value, placeholder: field.placeholder, onChange: function (e) { setField(e.target.value); } });
  }

  function FormEditor(props) {
    var value = props.value || {};
    function setField(key, v) { var next = Object.assign({}, value); next[key] = v; props.onChange(next); }
    function loadSample() { props.onChange(clone(props.sample)); }
    return h("div", null,
      h("div", { style: { display: "flex", gap: 8, marginBottom: 12 } },
        h(antd.Button, { size: "small", type: "primary", onClick: loadSample }, "一键填入示例数据"),
        h(antd.Button, { size: "small", danger: true, onClick: function () { props.onChange({}); } }, "清空")
      ),
      props.fields.map(function (field) {
        if (field.type === "subtable") {
          return h("div", { key: field.key, style: { marginBottom: 14 } },
            h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label + (field.required ? " *" : "")),
            editorFor(field, value[field.key], function (v) { setField(field.key, v); })
          );
        }
        return h("div", { key: field.key, style: { marginBottom: 14 } },
          h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label + (field.required ? " *" : "")),
          editorFor(field, value[field.key], function (v) { setField(field.key, v); })
        );
      }),
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 10 } }, props.hint) : null
    );
  }

  function ExtraInput(props) {
    var fields = props.fields || [];
    if (!fields.length) return null;
    return h("div", { style: { marginBottom: 12 } },
      fields.map(function (field) {
        return h("div", { key: field.key, style: { marginBottom: 10 } },
          h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label),
          h(antd.Input, { size: "small", value: field.value, placeholder: field.placeholder, onChange: function (e) { field.onChange(e.target.value); } })
        );
      })
    );
  }

  function AgentDock(props) {
    var listRef = useRef(null);
    useEffect(function () {
      if (listRef.current) listRef.current.scrollTop = listRef.current.scrollHeight;
    }, [props.messages]);
    if (!props.open) return null;
    return h("div", null,
      h("div", { className: "zy-mask", onClick: props.onClose }),
      h("div", { className: "zy-dock" },
        h("div", { className: "zy-chat" },
          h("div", { className: "zy-chat-head" },
            h("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 } },
              h("span", { style: { fontWeight: 650, fontSize: 15, color: T.text } }, "智能体助手 · " + (props.moduleLabel || "")),
              h("button", { "aria-label": "关闭", onClick: props.onClose, style: { border: "none", background: "transparent", cursor: "pointer", fontSize: 18, lineHeight: 1, color: T.sub, padding: "4px 8px", borderRadius: 6 } }, "✕")
            ),
            h("div", { className: "zy-tagline", style: { marginTop: 8 } }, "直接打字告诉我你要做什么，我会自动载入示例数据并运行对应模块。"),
            h("div", { className: "zy-chips", style: { marginTop: 10 } },
              props.modules.map(function (mod) {
                return h("span", { key: mod.key, className: "zy-chip", onClick: function () { props.onCommand(mod.key, mod.chipLabel); } }, mod.chipLabel || ("运行「" + mod.label + "」"));
              })
            )
          ),
          h("div", { className: "zy-chat-list", ref: listRef },
            (props.messages || []).map(function (msg, i) {
              return h("div", { key: i, className: "zy-msg " + (msg.role === "user" ? "zy-msg-user" : "zy-msg-bot") },
                h("div", { className: "zy-msg-bubble" }, msg.text),
                msg.card ? h("div", { className: "zy-msg-card" }, msg.card) : null
              );
            })
          ),
          h("div", { className: "zy-chat-input" },
            h(antd.Input, { value: props.draft, placeholder: "例如：帮我评估这3家供应商 / 计算补货量 / 监控风险", onChange: function (e) { props.setDraft(e.target.value); }, onPressEnter: function (e) { if (props.draft.trim()) { props.onSend(props.draft); e.preventDefault(); } } }),
            h(antd.Button, { type: "primary", style: { marginTop: 10, width: "100%" }, loading: props.busy, onClick: function () { if (props.draft.trim()) props.onSend(props.draft); } }, "发送")
          )
        )
      )
    );
  }

  function SupplyStudio() {
    var mods = [
  { key: "supplier", inputKind: "table", icon: "🏭", label: "供应商评估", short: "多维加权 · A/B/C/D 分级", chipLabel: "评估供应商", featNo: 16, keywords: ["供应商", "评估", "供货", "打分"],
    columns: [
      { key: "name", label: "供应商名称", required: true, width: 170, placeholder: "如：华南五金" },
      { key: "on_time_rate", label: "准时率%", type: "number", required: true, width: 110, min: 0, max: 100, step: 1, placeholder: "92" },
      { key: "quality_rate", label: "合格率%", type: "number", required: true, width: 110, min: 0, max: 100, step: 1, placeholder: "96" },
      { key: "price_index", label: "价格指数", type: "number", required: true, width: 110, min: 0, max: 3, step: 0.01, placeholder: "1.05" },
      { key: "service_score", label: "服务分", type: "number", width: 110, min: 0, max: 100, step: 1, placeholder: "85" }
    ],
    sample: [
      { name: "华南五金", on_time_rate: 92, quality_rate: 96, price_index: 1.05, service_score: 85 },
      { name: "明达包装", on_time_rate: 74, quality_rate: 82, price_index: 1.2, service_score: 66 },
      { name: "东江精密", on_time_rate: 88, quality_rate: 91, price_index: 0.98, service_score: 78 }
    ],
    hint: "录入真实供应商台账，系统按准时交付、来料合格、价格与服务加权打分并生成 A/B/C/D 分级与改进建议。",
    run: function (v) { return request(APP + "/artifacts/supplier", { suppliers: v }); },
    render: function (r) {
      var p = r.payload || {}; var rows = p.suppliers || [];
      var a = rows.filter(function (x) { return x.tier === "A"; }).length;
      var b = rows.filter(function (x) { return x.tier === "B"; }).length;
      var d = rows.filter(function (x) { return x.tier === "D"; }).length;
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "供应商数量", value: p.count, color: T.primary },
          { label: "A / B 级", value: a + " / " + b, color: T.green },
          { label: "D 级", value: d, color: T.red }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "供应商评估明细", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: "name", pagination: false, dataSource: rows, scroll: { x: true }, columns: [
            { title: "供应商", dataIndex: "name" },
            { title: "评分", dataIndex: "score", render: function (v) { return h("span", { style: { fontWeight: 650 } }, v); } },
            { title: "分级", dataIndex: "tier", render: function (v) { return h(antd.Tag, { color: v === "A" ? "green" : v === "B" ? "blue" : v === "C" ? "orange" : "red", style: { margin: 0 } }, v); } },
            { title: "准时率", dataIndex: "on_time_rate" },
            { title: "合格率", dataIndex: "quality_rate" },
            { title: "风险点", dataIndex: "issues", render: function (v) { return (v || []).join("、") || "无"; } }
          ]})
        )
      );
    }
  },
  { key: "replenishment", inputKind: "table", icon: "📦", label: "智能补货", short: "安全库存 · EOQ · 再订货点", chipLabel: "计算补货", featNo: 16, keywords: ["补货", "库存", "再订货", "需求", "安全库存", "订货"],
    columns: [
      { key: "sku", label: "物料编号", required: true, width: 120, placeholder: "如：AB123" },
      { key: "name", label: "物料名称", width: 140, placeholder: "如：铝合金型材" },
      { key: "annual_demand", label: "年需求", type: "number", required: true, width: 110, min: 0, step: 1, placeholder: "12000" },
      { key: "lead_time_days", label: "交期(天)", type: "number", required: true, width: 110, min: 1, max: 365, step: 1, placeholder: "9" },
      { key: "safety_days", label: "安全天数", type: "number", width: 110, min: 0, step: 1, placeholder: "5" },
      { key: "on_hand", label: "在手库存", type: "number", required: true, width: 110, min: 0, step: 1, placeholder: "120" },
      { key: "on_order", label: "在途", type: "number", width: 110, min: 0, step: 1, placeholder: "80" },
      { key: "order_cost", label: "订货成本", type: "number", width: 110, min: 0, step: 0.1, placeholder: "60" },
      { key: "unit_cost", label: "单位成本", type: "number", required: true, width: 110, min: 0, step: 0.01, placeholder: "18" },
      { key: "holding_rate", label: "持有率", type: "number", width: 110, min: 0, max: 1, step: 0.01, placeholder: "0.22" }
    ],
    sample: [
      { sku: "AB123", name: "铝合金型材", annual_demand: 12000, lead_time_days: 9, safety_days: 5, on_hand: 120, on_order: 80, order_cost: 60, unit_cost: 18, holding_rate: 0.22 },
      { sku: "CD456", name: "伺服驱动器", annual_demand: 3600, lead_time_days: 30, safety_days: 12, on_hand: 40, on_order: 0, order_cost: 140, unit_cost: 680, holding_rate: 0.18 }
    ],
    hint: "录入真实物料需求与库存，系统计算安全库存、再订货点、EOQ 与建议补货量，并标记库存状态。",
    run: function (v) { return request(APP + "/artifacts/replenishment", { items: v, method: "safety-stock-eoq-v1" }); },
    render: function (r) {
      var p = r.payload || {}; var rows = p.items || [];
      var urgent = rows.filter(function (x) { return x.status === "紧急补货"; }).length;
      var suggest = rows.filter(function (x) { return x.status === "建议补货"; }).length;
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "核算物料", value: rows.length, color: T.primary },
          { label: "紧急补货", value: urgent, color: T.red },
          { label: "建议补货", value: suggest, color: T.amber }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "补货决策建议", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: "sku", pagination: false, dataSource: rows, scroll: { x: true }, columns: [
            { title: "物料", dataIndex: "sku" },
            { title: "年需求", dataIndex: "annual_demand" },
            { title: "安全库存", dataIndex: "safety_stock" },
            { title: "再订货点", dataIndex: "reorder_point" },
            { title: "建议补货", dataIndex: "suggested_quantity" },
            { title: "状态", dataIndex: "status", render: function (v) { return h(antd.Tag, { color: statusColor(v), style: { margin: 0 } }, v); } }
          ]})
        )
      );
    }
  },
  { key: "risk", inputKind: "table", icon: "🚨", label: "风险监控", short: "交期质量 · 红黄绿分级", chipLabel: "监控风险", featNo: 30, keywords: ["风险", "监控", "预警", "交期", "物流", "合规"],
    columns: [
      { key: "order_no", label: "订单号", required: true, width: 170, placeholder: "如：PO-S-20260801" },
      { key: "supplier", label: "供应商", width: 140, placeholder: "如：深圳精工" },
      { key: "status", label: "状态", width: 120, type: "select", options: [{ value: "在途", label: "在途" }, { value: "待验收", label: "待验收" }, { value: "已签收", label: "已签收" }, { value: "异常", label: "异常" }], placeholder: "选择状态" },
      { key: "risk_note", label: "风险描述", required: true, width: 260, placeholder: "如：交期可能延期，物流在海运途中停滞" }
    ],
    sample: [
      { order_no: "PO-S-20260801", supplier: "深圳精工", status: "在途", risk_note: "交期可能延期，物流在海运途中停滞" },
      { order_no: "PO-S-20260802", supplier: "东江五金", status: "待验收", risk_note: "来料抽检不合格比例升高" },
      { order_no: "PO-S-20260803", supplier: "明达包装", status: "异常", risk_note: "供应商环保认证即将到期，存在合规风险" }
    ],
    hint: "录入真实订单与物流记录，系统做交期、质量、物流、价格、产能与合规风险打分，并按红黄绿分级给出处置建议。",
    run: function (v) { return request(APP + "/artifacts/risk", { records: v }); },
    render: function (r) {
      var p = r.payload || {}; var rows = p.records || [];
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "监控记录", value: p.count, color: T.primary },
          { label: "高风险", value: p.high_count || 0, color: T.red },
          { label: "中风险", value: p.medium_count || 0, color: T.amber }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "供应链风险分级", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: "order_no", pagination: false, dataSource: rows, scroll: { x: true }, columns: [
            { title: "订单", dataIndex: "order_no" },
            { title: "供应商", dataIndex: "supplier" },
            { title: "风险类型", dataIndex: "risk_category" },
            { title: "分数", dataIndex: "risk_score", render: function (v) { return h("span", { style: { fontWeight: 650 } }, v); } },
            { title: "级别", dataIndex: "severity", render: function (v) { return h(antd.Tag, { color: v === "high" ? "red" : v === "medium" ? "orange" : "green", style: { margin: 0 } }, v === "high" ? "高" : v === "medium" ? "中" : "低"); } },
            { title: "处置建议", dataIndex: "recommended_action", ellipsis: true }
          ]})
        )
      );
    }
  }
];

    var activeState = useState(mods[0].key);
    var active = activeState[0], setActive = activeState[1];
    var inputsState = useState({}), inputs = inputsState[0], setInputs = inputsState[1];
    var extrasState = useState({}), extras = extrasState[0], setExtras = extrasState[1];
    var resultsState = useState({}), results = resultsState[0], setResults = resultsState[1];
    var runningState = useState(null), running = runningState[0], setRunning = runningState[1];
    var reviewerState = useState(""), reviewer = reviewerState[0], setReviewer = reviewerState[1];
    var agentOpenState = useState(false), agentOpen = agentOpenState[0], setAgentOpen = agentOpenState[1];
    var draftState = useState(""), draft = draftState[0], setDraft = draftState[1];
    var messagesState = useState([]), messages = messagesState[0], setMessages = messagesState[1];
    var busyState = useState(false), busy = busyState[0], setBusy = busyState[1];
    var sourceState = useState("真实"), source = sourceState[0], setSource = sourceState[1];
    var message = antd.App.useApp().message;
    var activeMod = mods.find(function (m) { return m.key === active; });

    function setInput(key, value) { var next = Object.assign({}, inputs); next[key] = value; setInputs(next); }
    function setExtra(key, field, value) { var current = extras[key] || {}; var next = Object.assign({}, extras); var merged = Object.assign({}, current); merged[field] = value; next[key] = merged; setExtras(next); }
    function clearResult(key) { var next = Object.assign({}, results); delete next[key]; setResults(next); }

    function runModule(key, overrideValue) {
      var mod = mods.find(function (m) { return m.key === key; });
      var value = overrideValue !== undefined ? overrideValue : inputs[key];
      var extra = extras[key] || {};
      if (isBlank(value)) { message.warning("请先录入数据，或点击「一键导入示例数据」"); return Promise.reject(new Error("empty")); }
      setRunning(key);
      return Promise.resolve(mod.run(stripRid(value), stripRid(extra))).then(function (data) {
        var next = Object.assign({}, results); next[key] = data; setResults(next);
        message.success(mod.label + "：已生成待审阅工件");
        return data;
      }).catch(function (e) { message.error(e.message || "执行失败"); throw e; }).finally(function () { setRunning(null); });
    }

    function decide(key, action) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件"); return; }
      if (!reviewer.trim()) { message.warning("请输入具名审阅人"); return; }
      var review = mod.review ? mod.review(result, action, reviewer) : request(APP + "/artifacts/" + result.id + "/reviews", { action: action, reviewer: reviewer });
      Promise.resolve(review).then(function (data) {
        var next = Object.assign({}, results); next[key] = data; setResults(next);
        message.success(action === "accept" ? "工件已接受" : "工件已驳回");
      }).catch(function (e) { message.error(e.message); });
    }

    function exportArtifact(key) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件"); return; }
      if (mod.exportFn) { mod.exportFn(result); return; }
      if (result.status !== "accepted") { message.warning("工件需先被接受"); return; }
      window.open(APP + "/artifacts/" + result.id + "/export", "_blank");
    }

    function handoff(key) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件再交给 Agent"); return; }
      pushAgentContext({ label: mod.label, app_id: ID, artifact_id: result.id || result.ticket_id, kind: key, summary: result, source_type: source === "演示" ? "simulated" : "real" });
      message.success("已将「" + mod.label + "」结果加入 Agent 上下文");
    }

    function detectModule(text) {
      var t = text.toLowerCase();
      for (var i = 0; i < mods.length; i++) {
        var mod = mods[i];
        for (var j = 0; j < (mod.keywords || []).length; j++) {
          if (t.indexOf(mod.keywords[j]) >= 0) return mod.key;
        }
      }
      return mods[0].key;
    }

    function artifactCard(key, data) {
      var mod = mods.find(function (m) { return m.key === key; });
      var status = data.status || "pending_review";
      return h("div", null,
        h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 } },
          h("strong", { style: { fontSize: 12.5 } }, mod.label),
          h(antd.Tag, { color: statusTone(status).color, style: { margin: 0 } }, statusTone(status).text)
        ),
        h("div", { className: "zy-tagline" }, "工件已生成：" + (data.id || data.ticket_id || "")),
        h("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
          h(antd.Button, { size: "small", type: "primary", onClick: function () { setActive(key); setAgentOpen(false); } }, "查看结果"),
          h(antd.Button, { size: "small", onClick: function () { handoff(key); } }, "交给 Agent")
        )
      );
    }

    function agentCommand(key, prompt) {
      var mod = mods.find(function (m) { return m.key === key; });
      setMessages(function (prev) { return prev.concat([{ role: "user", text: prompt || mod.label }]); });
      setBusy(true); setActive(key);
      if (isBlank(inputs[key])) {
        setInput(key, clone(sampleFor(mod)));
        message.info("已载入示例数据，可替换为真实业务数据");
      }
      setTimeout(function () {
        runModule(key, sampleFor(mod)).then(function (data) {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: mod.label + "：已生成可审阅工件，请切换回界面确认结果。", card: artifactCard(key, data) }]); });
        }).catch(function () {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "执行失败，请检查输入后重试。" }]); });
        }).finally(function () { setBusy(false); });
      }, 300);
    }

    function agentSend(text) {
      setMessages(function (prev) { return prev.concat([{ role: "user", text: text }]); });
      setBusy(true);
      var key = detectModule(text);
      var mod = mods.find(function (m) { return m.key === key; });
      setActive(key);
      if (isBlank(inputs[key])) { setInput(key, clone(sampleFor(mod))); message.info("已载入示例数据，可替换为真实业务数据"); }
      setTimeout(function () {
        runModule(key, sampleFor(mod)).then(function (data) {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "已为你执行「" + mod.label + "」，下方是结果摘要，可回界面审阅与导出。", card: artifactCard(key, data) }]); });
        }).catch(function () {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "执行「" + mod.label + "」出现问题，请检查输入后重试。" }]); });
        }).finally(function () { setBusy(false); });
      }, 300);
    }

    function renderInput(mod) {
      if (mod.inputKind === "text") {
        return h(InputText, { value: inputs[mod.key], example: mod.example, placeholder: mod.placeholder, rows: mod.rows, hint: mod.hint, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } });
      }
      if (mod.inputKind === "form") {
        return h(FormEditor, { fields: mod.fields, value: inputs[mod.key], sample: mod.sample, hint: mod.hint, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } });
      }
      return h("div", null,
        h(ExtraInput, { fields: (mod.extraInputs || []).map(function (f) { return { key: f.key, label: f.label, placeholder: f.placeholder, value: (extras[mod.key] || {})[f.key], onChange: function (v) { setExtra(mod.key, f.key, v); setSource("真实"); } }; }) }),
        h(EditableTable, { icon: mod.icon, columns: mod.columns, value: inputs[mod.key], sample: mod.sample, hint: mod.hint, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } }),
        (mod.extraTable || []).map(function (t) {
          return h("div", { key: t.key, style: { marginTop: 14 } },
            h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, t.label + "（可选）"),
            h(EditableTable, { icon: t.icon, columns: t.columns, value: (extras[mod.key] || {})[t.key], sample: t.sample, hint: t.hint, onChange: function (v) { setExtra(mod.key, t.key, v); setSource("真实"); } })
          );
        })
      );
    }

    function renderResult(mod) {
      var result = results[mod.key];
      var isRunning = running === mod.key;
      if (isRunning) {
        return h("div", { style: { padding: "42px 0", textAlign: "center" } },
          h(antd.Spin, { tip: "智能引擎分析中…" }),
          h("div", { style: { fontSize: 12, color: T.sub, marginTop: 10 } }, "正在结合模型计算并生成可审阅结果")
        );
      }
      if (!result) {
        return h(EmptyState, { icon: mod.icon, title: "暂无分析结果", desc: "在左侧填入真实数据后点击「" + (mod.chipLabel || "开始分析") + "」，系统会生成带证据的可审阅工件。" });
      }
      var reviewable = mod.reviewable !== false;
      return h(Fragment, null,
        mod.render(result),
        h("div", { style: { display: "flex", alignItems: "center", gap: 8, marginTop: 14, fontSize: 12, color: T.sub } },
          h("span", { className: "zy-status-dot", style: { background: T.green } }),
          "数据来源：" + source + "，基于真实业务输入生成，演示数据已明确标注。"
        ),
        reviewable ? h(ReviewBar, { status: result.status, traceId: result.id, reviewer: reviewer, setReviewer: setReviewer, onDecide: function (a) { decide(mod.key, a); }, onExport: function () { exportArtifact(mod.key); }, onHandoff: function () { handoff(mod.key); } })
          : h("div", { style: { marginTop: 14 } }, h(antd.Button, { size: "small", onClick: function () { handoff(mod.key); } }, "交给 Agent"))
      );
    }

    return h("div", { className: "zy-app" },
      h(AppHeader, { source: source, refreshing: false, onRefresh: function () { setSource("真实"); message.success("已刷新最新数据"); }, onAgent: function () { setAgentOpen(true); } }),
      h("div", { className: "zy-body" },
        h(ModuleNav, { modules: mods, active: active, onSelect: function (key) { setActive(key); } }),
        h("div", { className: "zy-main" },
          h("div", { key: active, className: "zy-fade" }, activeMod ? h("div", { className: "zy-cols" },
            h("div", { className: "zy-panel" },
              h("div", { className: "zy-panel-head" },
                h("div", null, h("div", { className: "zy-panel-title" }, activeMod.label), h("div", { className: "zy-panel-sub" }, activeMod.short)),
                h(antd.Tag, { color: "blue", style: { margin: 0 } }, "功能 " + activeMod.featNo)
              ),
              h("div", { className: "zy-panel-body" },
                renderInput(activeMod),
                h("div", { style: { display: "flex", gap: 8, marginTop: 14 } },
                  h(antd.Button, { className: "zy-run", type: "primary", size: "large", loading: running === activeMod.key, onClick: function () { runModule(activeMod.key); } }, activeMod.chipLabel || "开始分析"),
                  h(antd.Button, { size: "large", onClick: function () { setInput(activeMod.key, null); clearResult(activeMod.key); setSource("真实"); } }, "清空")
                )
              )
            ),
            h("div", { className: "zy-panel" },
              h("div", { className: "zy-panel-head" },
                h("div", null, h("div", { className: "zy-panel-title" }, "分析结果"), h("div", { className: "zy-panel-sub" }, "结果可审阅、导出或交给 Agent")),
                h(antd.Tag, { color: source === "演示" ? "purple" : "blue", style: { margin: 0 } }, source + "数据")
              ),
              h("div", { className: "zy-panel-body" }, renderResult(activeMod))
            )
          ) : null)
        )
      ),
      h(AgentDock, { open: agentOpen, onClose: function () { setAgentOpen(false); }, modules: mods, moduleLabel: activeMod ? activeMod.label : "", messages: messages, draft: draft, setDraft: setDraft, busy: busy, onSend: agentSend, onCommand: agentCommand })
    );
  }

  Q.registerRoutes(ID, [{ path: "/apps/" + ID, component: SupplyStudio, label: APP_TITLE, icon: "🚚", priority: 82 }]);
})();
